#!/bin/bash

# スクリーンショット撮影ガイド - リアルタイム実行版

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  📸 BPMSetlist スクリーンショット撮影開始              ║"
echo "║  手動実行モード - 画面の指示に従ってください          ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# デスクトップに保存用フォルダを作成
DESKTOP="$HOME/Desktop"
OUTPUT_DIR_IPHONE="$DESKTOP/AppStore-Screenshots-iPhone"
OUTPUT_DIR_IPAD="$DESKTOP/AppStore-Screenshots-iPad"

mkdir -p "$OUTPUT_DIR_IPHONE"
mkdir -p "$OUTPUT_DIR_IPAD"

echo "✅ 準備完了！"
echo ""
echo "📁 保存先フォルダを作成しました:"
echo "   - iPhone用: $OUTPUT_DIR_IPHONE"
echo "   - iPad用:   $OUTPUT_DIR_IPAD"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 STEP 1: iPhoneでスクリーンショットを撮影"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Xcodeが開いていることを確認してください"
echo ""
echo "2. デバイスを選択:"
echo "   Xcode上部のデバイス選択 → 【iPhone 15 Pro Max】を選択"
echo ""

read -p "デバイスを選択しましたか? (Enter キーを押して続行)" 

echo ""
echo "3. アプリを実行:"
echo "   ⌘R または Playボタンをクリック"
echo ""

read -p "アプリが起動しましたか? (Enter キーを押して続行)"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📸 5つの画面をスクリーンショット撮影します"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 画面1
echo "【画面 1/5】メイン画面（空の状態）"
echo ""
echo "操作: そのままの状態でOK"
echo "撮影: シミュレーターをクリックして ⌘S を押す"
echo ""
read -p "撮影しましたか? (Enter)" 

# 画面2
echo ""
echo "【画面 2/5】曲を追加した状態"
echo ""
echo "操作: + ボタンをタップ → 曲情報を入力"
echo "      例: Shape of You, Ed Sheeran, 96"
echo "      保存ボタンをタップ"
echo "撮影: ⌘S を押す"
echo ""
read -p "撮影しましたか? (Enter)" 

# 画面3
echo ""
echo "【画面 3/5】曲追加画面"
echo ""
echo "操作: 再度 + ボタンをタップ"
echo "撮影: ⌘S を押す"
echo "      その後、キャンセルで閉じる"
echo ""
read -p "撮影しましたか? (Enter)" 

# 画面4
echo ""
echo "【画面 4/5】再生中の画面"
echo ""
echo "操作: 再生ボタン（▶）をタップ"
echo "撮影: ⌘S を押す"
echo ""
read -p "撮影しましたか? (Enter)" 

# 画面5
echo ""
echo "【画面 5/5】設定画面"
echo ""
echo "操作: 設定ボタン（⚙）をタップ"
echo "撮影: ⌘S を押す"
echo ""
read -p "撮影しましたか? (Enter)" 

echo ""
echo "✅ iPhone用スクリーンショット完了！"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 STEP 2: iPadでスクリーンショットを撮影"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. デバイスを変更:"
echo "   Xcode上部のデバイス選択 → 【iPad Pro (12.9-inch)】を選択"
echo ""

read -p "デバイスを変更しましたか? (Enter)" 

echo ""
echo "2. アプリを再実行:"
echo "   ⌘R でアプリを起動"
echo ""

read -p "アプリが起動しましたか? (Enter)"

echo ""
echo "3. 同じ5つの画面を撮影してください"
echo "   (iPhone と同じ手順を繰り返す)"
echo ""

# iPad用の画面
for i in {1..5}; do
    echo "【画面 $i/5】"
    read -p "撮影しましたか? (Enter)" 
done

echo ""
echo "✅ iPad用スクリーンショット完了！"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📂 STEP 3: スクリーンショットを整理"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "デスクトップに保存されたスクリーンショットを整理します"
echo ""

# デスクトップのスクリーンショットフォルダを開く
open "$DESKTOP"
open "$OUTPUT_DIR_IPHONE"
open "$OUTPUT_DIR_IPAD"

echo "1. Finderが開きました"
echo ""
echo "2. デスクトップのスクリーンショットを確認:"
echo "   - 最初の5枚（iPhone）→ AppStore-Screenshots-iPhone フォルダへ移動"
echo "   - 次の5枚（iPad）→ AppStore-Screenshots-iPad フォルダへ移動"
echo ""
echo "3. ファイル名をリネーム（推奨）:"
echo "   01-main-empty.png"
echo "   02-with-songs.png"
echo "   03-add-song.png"
echo "   04-playing.png"
echo "   05-settings.png"
echo ""

read -p "整理が完了しましたか? (Enter)" 

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  🎉 スクリーンショット撮影完了！                      ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "📁 保存場所:"
echo "   iPhone: $OUTPUT_DIR_IPHONE"
echo "   iPad:   $OUTPUT_DIR_IPAD"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📤 次のステップ: App Store Connect にアップロード"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. App Store Connect にアクセス:"
echo "   https://appstoreconnect.apple.com/"
echo ""
echo "2. アプリを選択 → 1.0 準備中 → スクリーンショット"
echo ""
echo "3. 'View All Sizes in Media Manager' をクリック"
echo ""
echo "4. iPhone用:"
echo "   $OUTPUT_DIR_IPHONE から5枚をドラッグ&ドロップ"
echo "   → 6.7インチ (iPhone 15 Pro Max) のスロットに配置"
echo ""
echo "5. iPad用:"
echo "   $OUTPUT_DIR_IPAD から5枚をドラッグ&ドロップ"
echo "   → 12.9インチ (iPad Pro) のスロットに配置"
echo ""
echo "6. 保存 → Submit for Review"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ これでApp Storeの要件を満たしました！"
echo "✅ iPhone版とiPad版が別々のデバイスで撮影されています"
echo ""
echo "Good luck! 🚀"
echo ""
